### PR TITLE
Enable skipping conversations parsing

### PR DESCRIPTION
**Pull request by williamdes**

### CODE REVIEW

**Comment by iulspop** [comment]
Hi @williamdes, currently, conversations are already skipped if the `CONVERSATION_NAMES` env variable is unset. It seems that you are mixing two concepts. "Conversations" is the name for private DM conversations. "Threads" is the name for Slack posts with replies.

Your pull request means to add the option for disabling scraping threads but mixes that option with whether the `CONVERSATION_NAMES`  env variable is set.

We could add a separate env variable for disabling scraping threads, but I wonder if that's necessary? I replied to your issue #1 about how scraping threads fails in French. Wouldn't fixing that by switching to English mean it's no longer necessary to disable scraping threads?

Let me know, thanks :)

**Comment by williamdes** [comment]
> Hi @williamdes, currently, conversations are already skipped if the `CONVERSATION_NAMES` env variable is unset. It seems that you are mixing two concepts. "Conversations" is the name for private DM conversations. "Threads" is the name for Slack posts with replies.
> 
> Your pull request means to add the option for disabling scraping threads but mixes that option with whether the `CONVERSATION_NAMES` env variable is set.
> 
> We could add a separate env variable for disabling scraping threads, but I wonder if that's necessary? I replied to your issue #1 about how scraping threads fails in French. Wouldn't fixing that by switching to English mean it's no longer necessary to disable scraping threads?
> 
> Let me know, thanks :)

Oh okay, Indeed, I understand better now. Maybe I can add an ENV for that. For example at work people talk on some announcements and I really do not want to waste time and ressources fetching the comments as my goal was to extract the announcement list. That said I will probably have to add the feature to parse emojis. Because we use emojis to track states of things that are asked in a channel. So in this channel it is usefull to fetch threads and store them.

By the way I found that the HTML was crap for my usage and added an html to markdown code. Let me know if you want me to add this and if it should have an ENV.

## Example data

On the channel #bugs an user posts "there is a bug in foo for the menu". Devs add tracking emojis and bookmark it.
When done we create an announcement in the #announcements channel to say foo: fixed the menu (https slack link to the #bugs channel post)"

## Goal 1

Fetch and parse the announcement list. Done with a bit of `jq` magic and the html to markdown feature 🎉 

## Goal 2

Fetch the things that are asked channel and the threads.
Get the emojis for them.
And if possible find a way to have the message Ids so I can link announcements to questions when I render to markdown the questions channel

**Comment by iulspop** [comment]
> Maybe I can add an ENV for that. For example at work people talk on some announcements and I really do not want to waste time and ressources fetching the comments as my goal was to extract the announcement list.

That sounds like a legitimate use case. Feel free to update this pull request to add an env variable for disabling scraping posts.

> By the way I found that the HTML was crap for my usage and added an html to markdown code. Let me know if you want me 
to add this and if it should have an ENV.

Yup, the parsing script is still a work in progress. I've meant to add a parsing step to take the HTML output under the post text property and convert it to Markdown. I would appreciate it if you opened a pull request for that!

> Devs add tracking emojis

It sounds like you mean emoji reactions to posts instead of emojis used in the post text. Is that correct? I believe the raw HTML scraped from the channel/DM posts already contains the emoji reactions. However, the parsing script currently doesn't extract that data and add it to the post object. If you wish to implement that, it can be accomplished in the `parsePostsToJson/index.js` file. I'm open to your contributions if you want to improve this project!

**Comment by williamdes** [comment]
I have all this still pinned and TODO ;)

**Comment by iulspop** [comment]
Good to hear! I believe it's better to open a pull request for each of the individual features you mentioned when you're ready, as you already have for skipping threads parsing #4.

**Pull request closed without merging**
