### PR TITLE
New feature: skip threads parsing

### PR DESCRIPTION
**Pull request by williamdes**
Ref: #2

### CODE REVIEW

**Comment by williamdes** [comment]
💤 Will continue tomorrow if your review needs changes ;)

**Comment by iulspop** [comment]
Can you refactor this to access the `SKIP_THREADS` env var directly in `extractPostsHTML.js` instead of passing it down from `scrape/index.js`?

**Review by williamdes — COMMENTED** [review]
Just checked and this is working fine on my workstation

**Comment by williamdes** [comment]
> Can you refactor this to access the `SKIP_THREADS` env var directly in `extractPostsHTML.js` instead of passing it down from `scrape/index.js`?

Done, sorry for the very long delay

**Comment by iulspop** [comment]
Thanks! I will review this soon.

**Comment by iulspop** [comment]
Great PR! Thanks for adding this feature :)

**Pull request merged**
